### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by tyler43636** [TippingCanoe/imager#1]
I'm looking at adding an amazon S3 driver. Would you be interested in pulling it in if I get it working?

**Comment by atrauzzi** [comment]
Definitely, I can help out with any questions you might have.  Be sure to add yourself to `contributors.md` in your branch as well! :+1:

**Comment by tyler43636** [comment]
I have a working Amazon S3 driver on my branch. Can you help me set the properties from the Imager config file? Right now I am just hard coding them into the constructor. Here is the commit with the S3 class: https://github.com/tyler43636/imager/commit/a47e272eb373da5120495d416d594b4ca2352c66

**Comment by tyler43636** [comment]
I was able to get the properties set from the config file using the method you used on the filesystem drive. Now my problem is that they are not initialized during object creation so I can't instantiate the S3 client in the constructor. Do you know of a good technique I can use to create the S3 client so I don't need to call some sort of 'makeS3()' method in every method I want to use it?

**Comment by tyler43636** [comment]
Submitted pull request.

https://github.com/TippingCanoe/imager/pull/2
