### ISSUE TITLE
getPublicUriBySlot not working

### ISSUE THREAD

**Issue by tyler43636** [TippingCanoe/imager#4]
# This doesn't work

```
$album = Album::find(1);
return Imager::getPublicUriBySlot('album-cover', $album);
```
# But this does

```
$album = Album::find(1);
$image = Imager::getBySlot('album-cover', $album);
return Imager::getPublicUri($image);
```
# Here is the error. Any ideas?
## ErrorException

Argument 1 passed to TippingCanoe\Imager\Service::getPublicUri() must be an instance of TippingCanoe\Imager\Model\Image, instance of Illuminate\Database\Eloquent\Relations\MorphMany given, called in /Users/tyler/www/photo/vendor/tippingcanoe/imager/src/TippingCanoe/Imager/Service.php on line 124 and defined

**Comment by atrauzzi** [comment]
Try ->first() where you're calling the method.  Looks like you might be passing in the relation before it's been executed?

**Comment by atrauzzi** [comment]
Hopefully that helped! :)
